name: Build for pull request

on:
  pull_request:
    branches: [aio]

env:
  NODE_ENV: production
  NODE_VERSION: 17

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: build
        run: npm install -g yarn && yarn build
      - name: push
        run: git
