name: Build for pull request

on:
  pull_request:
    branches: [ aio ]

env:
  NODE_ENV: production
  NODE_VERSION: 17

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: build
        run: npm install -g yarn && yarn build
      - name: pull
        run: git clone git@github.com:ng-docs/preview.angular.cn.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: update
        run: cp -r aio/dist/* preview.angular.cn/
      - name: push
        run: cd preview.angular.cn && git add . && git commit -m "update" && git push
